### ISSUE TITLE
upgrade depends, flutter_quill > 8

### ISSUE THREAD

**Issue by marcio-ota** [sabeeralikp/delta_to_pdf#3]
Please upgrade depends, flutter_quill > 8

**Comment by sabeeralikp** [comment]
Upgraded to flutter_quill 9.3.1

**Comment by dubemezeagwu** [comment]
Great and essential package! 👍🏽

When will version 0.0.7 be available on pub.dev?
I am currently facing versioning issues with using the package and from the resolved issue, it seems this has already been addressed to accommodate newer versions of flutter_quill.
